export const hotelData = [
	{
		id: 1,
		name: 'Teena Greenier',
		avail: 'cancellation flexibility available',
		detail: '4 guest 2 bedrooms 2 beds 2 baths with air conditioning kitchen',
		price: 37,
		ratings: 4.9,
		img: '/images/hotel1.png',
		icon: '/images/Icon/star.png',
	},
	{
		id: 2,
		name: 'Lea Skiplorne',
		avail: 'cancellation flexibility available',
		detail: '4 guest 2 bedrooms 2 beds 2 baths with air conditioning kitchen',
		price: 52,
		ratings: 4.3,
		img: '/images/hotel2.png',
		icon: '/images/Icon/star.png',
	},
	{
		id: 3,
		name: 'Derick Bradshaw',
		avail: 'cancellation flexibility available',
		detail: '4 guest 2 bedrooms 2 beds 2 baths with air conditioning kitchen',
		price: 43,
		ratings: 4.5,
		img: '/images/hotel3.png',
		icon: '/images/Icon/star.png',
	},
];
